### ISSUE TITLE
Server-relative link to destination project

### ISSUE THREAD

**Issue by mikecharles** [trac-hacks/TicketMoverPlugin#3]
Instead of a direct link in URL format to the destination project, would it possible to use the [TracLinks](http://trac.edgewall.org/wiki/TracLinks) syntax for server-relative links? Otherwise if I move my Trac environments to a new server all the links will be wrong.

**Comment by UnwashedMeme** [comment]
As an aside: I recommend creating a DNS name for trac like trac.acceleration.net so that even if you move the installation between servers you can just change the DNS entry and you're still stable.

Can you be a bit more specific where you're seeing the absolute url? Is this the comment left behind on the old ticket when moved to somewhere else?
I.e. https://github.com/UnwashedMeme/TicketMoverPlugin/blob/acceleration/ticketmoverplugin.py#L211 that condition shouldn't be there and we should always use the else clause?

**Comment by mikecharles** [comment]
Yes, that's what I meant. In the comment of the source ticket it says
"moved to http://hardcodedserver/project2", and in the destination ticket
it says "moved from http://hardcodedserver/project1".

I'd rather it uses this syntax:

"moved to [[//project2]]"

Thanks for the DNS suggestion, but unfortunately I have no control over
that here at my job :-/

On Fri, Mar 21, 2014 at 10:34 AM, Nathan Bird notifications@github.comwrote:

> As an aside: I recommend creating a DNS name for trac like
> trac.acceleration.net so that even if you move the installation between
> servers you can just change the DNS entry and you're still stable.
> 
> Can you be a bit more specific where you're seeing the absolute url? Is
> this the comment left behind on the old ticket when moved to somewhere else?
> I.e.
> https://github.com/UnwashedMeme/TicketMoverPlugin/blob/acceleration/ticketmoverplugin.py#L211that condition shouldn't be there and we should always use the else clause?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/UnwashedMeme/TicketMoverPlugin/issues/3#issuecomment-38280744
> .

## 

Mike Charles

Video Game Composer
http://www.mikecharlesmusic.com
